FROM python:3.6
WORKDIR /app

#RUN mkdir ./flask-server
COPY flask-server/ ./
RUN pip install -r requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
#WORKDIR /flask-server/api
CMD ["gunicorn", "-b", "0.0.0.0:5000", "server:app"]
#CMD ["python", "server.py"]

